language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.7.0
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
os:
  - linux
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - nvm install 10
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
env:
  global:
    - TEST=true
script:
  - bundle exec rake test